# Generated by Django 2.0.8 on 2020-12-03 01:49

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mtuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='mtuser',
            name='avatar',
            field=models.CharField(max_length=200, null=True, verbose_name='头像链接'),
        ),
        migrations.AlterField(
            model_name='mtuser',
            name='telephone',
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name='手机号码'),
        ),
    ]
