# Generated by Django 2.0.8 on 2020-12-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtauth', '0002_auto_20201203_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtuser',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='邮箱'),
        ),
    ]
