# Generated by Django 2.0.8 on 2020-12-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_auth',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='active_code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='激活码'),
        ),
    ]
