# Generated by Django 2.0.8 on 2020-12-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0002_auto_20201222_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='激活时间'),
        ),
    ]
