# Generated by Django 2.0.8 on 2020-12-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meituan', '0002_auto_20201202_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='经度'),
        ),
    ]
