# Generated by Django 2.0.8 on 2020-12-02 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meituan', '0003_auto_20201202_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='created',
            new_name='creator',
        ),
    ]
